---
- hosts: all
  become: true
  tasks:
    - name: Install Apache and tools
      yum:
        name:
          - httpd
          - mod_ssl
        state: present

    - name: Ensure Apache is running and enabled
      systemd:
        name: httpd
        state: started
        enabled: true
