---
- hosts: all
  become: yes

  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: present

  - name: Start and enable Apache
    systemd:
      name: httpd
      enabled: yes
      state: started
